# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev2+ge3b31c4.d20221114'
__version_tuple__ = version_tuple = (0, 1, 'dev2', 'ge3b31c4.d20221114')
